version: "3.5"

# https://docs.docker.com/compose/compose-file/

services:
  bods-json:
    container_name: bods-json
    restart: unless-stopped
    build: .
    image: bods-json
    logging:
      driver: json-file
      options:
        max-size: "1024k"
        max-file: "10"
    network_mode: host
    expose:
      - 5000
    ports:
      - 5000:80
